### ISSUE TITLE
インスタ投稿を自動化する

### ISSUE THREAD

**Issue by YuyaKurosaki0121** [meyco-inc/desk#22]
以下サイト内から一つツールを選択し、真珠肌の投稿を自動化する。
https://insta-antenna.com/reservation-posting-tool

**Comment by meyco-yamamotoshinya** [comment]
・4/20（土）23:59までにする（黒崎）

**Comment by YuyaKurosaki0121** [comment]
@meyco-yamamotoshinya 
こちらに関して、以下のツールを使用することに致しました。

- https://hootsuite.com/ja/

理由としては、以下3点です。

- 一ヶ月の無料トライアルがある点
- 日本語対応をしている点

- 他のツールと比較した場合、利用できる機能が多い

無料トライアルが5月14日終了のため、5月13日に継続か否かの共有をします
