### ISSUE TITLE
スラック内に広告運用に関しての行った行動のログとして残すチャンネルを構築する

### ISSUE THREAD

**Issue by YuyaKurosaki0121** [meyco-inc/desk#30]
# Why
- いつどのようなことをしたのか情報をキャッチアップするには、スラックの投稿を遡らなくてはいけないため、工数がかかる

# What
- ログが残るチャンネルを作成する

# メモ
http://www.randpy.tokyo/entry/slack_google_adsense

**Comment by meyco-yamamotoshinya** [comment]
・どうやったらできるか理解（黒崎）：4/19（金）23:59
・作戦の構築（黒崎）：4/21（日）23:59
・実行：（黒崎）：？
