### ISSUE TITLE
kibela

### ISSUE THREAD

**Issue by meyco-yamamotoshinya** [meyco-inc/desk#33]

**Comment by meyco-yamamotoshinya** [comment]
[黒崎](http://d.hatena.ne.jp/keyword/%A5%C1%A5%E3%A5%A4%A5%CB%A1%BC%A5%BA)

**Comment by YuyaKurosaki0121** [comment]
# WHY
 * 情報が一元管理されていないため、キャッチアップするのに時間がかかる。またどの情報がどこにあるのかわかっていない。
# WHAT
* esaに情報を集約する
# TODO
esaにて階層を作成し、どこにどんな情報を記載するのか明確にする。

**Comment by meyco-yamamotoshinya** [comment]
esaにて階層を作成し、どこにどんな情報を記載するのか明確にする。
　・全社MTG（全員）
　　・階層決め
　　・esaルール決め
　　　・マークダウン使用
　　　・体言止め徹底
　　　・日報記載
　・現情報の収集（黒崎）
　・esaにアウトプット（黒崎）

**Comment by meyco-yamamotoshinya** [comment]
[古山](http://www.asahicom.jp/articles/images/AS20181130004177_comm.jpg)
