### ISSUE TITLE
会社にとって有益な情報が流れるチャンネルを作成する。

### ISSUE THREAD

**Issue by YuyaKurosaki0121** [meyco-inc/desk#38]
# why
情報収集の時間が取れないので、会社にとって有益な情報（中国・インフルエンサー・広告・サイト制作・デザイン等）を自動で取得出来るようにしたい。

# what
指定したサイトにて投稿された場合、Slackの指定したチャンネルのその情報が投稿されるようにする

# How
zappierにてトリガーを1.new item in feedにてサイトを選択
2.actionにてsend channel messageを選択

**Comment by meyco-yamamotoshinya** [comment]
# チャンネル追加
* fyi_china
* fyi_marketing
* fyi_service
* fyi_enterprise
* fyi_other
# ifs追加
* 4/21（日）19:00まで（黒崎）

**Comment by YuyaKurosaki0121** [comment]
https://vacks.paid.jp/?p=3800
