### ISSUE TITLE
レポートの自動化

### ISSUE THREAD

**Issue by meyco-yamamotoshinya** [meyco-inc/desk#41]
▼目的
　・全媒体のレポートの自動化

▼スケジュール
　・記事送付（古山：4/18 23:59）
　・実行（黒崎：4/21 23:59）
　・改善（古山：4/30 23:59）→FIX

**Comment by YuyaKurosaki0121** [comment]
@meyco-yamamotoshinya これ、真也ボールだと思うので、アサイン変更しておきます！

**Comment by meyco-yamamotoshinya** [comment]
どう俺ボールなんだけ？

**Comment by meyco-yamamotoshinya** [comment]
@YuyaKurosaki0121
